import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import Image from 'next/image'
import salman from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web2.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web2.png'
import web5 from '../public/web2.png'
import web6 from '../public/web2.png'
import { useState, useEffect} from 'react'
import Modal from './Modal'

export default function Home() {
  const [darkMode, setdarkMode] = useState(false)
  const [openModal, setOpenModal] = useState(false)

  useEffect(() => { 
      setOpenModal(true)
  }, [])
  
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Modal open={openModal} onClose={()=> {
        setOpenModal(false)
      }}/>
      <Head>
        <title>Salman's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-slate-800'>
        <section className='min-h-screen'>

          <nav className='py-10 mb-12 flex justify-between px-2'>
          <h1 className='text-xl dark:text-slate-50'>developedbysal</h1>
          <ul className='flex items-center'>
            <li>
            <BsFillMoonStarsFill onClick={()=>{setdarkMode(!darkMode)}} className='cursor-pointer text-2xl dark:text-slate-50'/>
            </li>
            <li>
              <a className='bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8' href='#'>
                Resume
              </a>
            </li>
          </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-200 font-medium'>Salman Shahid</h2>
            <h3 className='text-2xl py-2 dark:text-slate-50 my-2'>Developer and Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-slate-50'>Freelancer providing services for programming and design content needs. 
              Join me down below and let's get cracking!</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-13 text-gray-600 dark:text-slate-50'>
            <AiFillLinkedin/>
            <AiFillTwitterCircle/>
            <AiFillYoutube/>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={salman} fill={true} style={{objectFit: 'cover'}}/>
          </div>
        </section>
        {/* Section 2 */}
        <section>
        <div>
            <h3 className="text-3xl py-1 dark:text-white my-8">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className='md:flex gap-10 dark:text-slate-50'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-slate-900'>
              <Image src={design} width={100} height={100} className='mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegant designs suited for your needs following core
                design theory.</p>
                <h4 className='py-4 text-teal-600'>Design tools I use</h4>
                <p className='text-gray-800 py-1 dark:text-slate-50'>Photoshop</p>
                <p className='text-gray-800 py-1 dark:text-slate-50'>Illustrator</p>
                <p className='text-gray-800 py-1 dark:text-slate-50'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-slate-900'>
              <Image src={code} width={100} height={100} className='mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegant designs suited for your needs following core
                design theory.</p>
                <h4 className='py-4 text-teal-600'>Design tools I use</h4>
                <p className='text-gray-800 py-1 dark:text-slate-50'>Photoshop</p>
                <p className='text-gray-800 py-1 dark:text-slate-50'>Illustrator</p>
                <p className='text-gray-800 py-1 dark:text-slate-50'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-slate-900'>
              <Image src={consulting} width={100} height={100} className='mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegant designs suited for your needs following core
                design theory.</p>
                <h4 className='py-4 text-teal-600'>Design tools I use</h4>
                <p className='text-gray-800 py-1 dark:text-slate-50'>Photoshop</p>
                <p className='text-gray-800 py-1 dark:text-slate-50'>Illustrator</p>
                <p className='text-gray-800 py-1 dark:text-slate-50'>Figma</p>
            </div>
          </div>
        </section>
        {/* Section 3 */}
        <div>
        <section className='dark:text-slate-50'>
        <h3 className='text-3xl py-1'>Portfolio</h3>
        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
            <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
              <div className='basis-1/3 flex-1 '>
                <Image src={web1} className=" rounded-lg object-cover" width={'100%'} height={"100%"} layout={'responsive'}/>
              </div>
              <div className='basis-1/3 flex-1 '>
                <Image src={web2} className=" rounded-lg object-cover" width={'100%'} height={"100%"} layout={'responsive'}/>
              </div>
              <div className='basis-1/3 flex-1 '>
                <Image src={web3} className=" rounded-lg object-cover" width={'100%'} height={"100%"} layout={'responsive'}/>
              </div>
              <div className='basis-1/3 flex-1 '>
                <Image src={web4} className=" rounded-lg object-cover" width={'100%'} height={"100%"} layout={'responsive'}/>
              </div>
              <div className='basis-1/3 flex-1 '>
                <Image src={web5} className=" rounded-lg object-cover" width={'100%'} height={"100%"} layout={'responsive'}/>
              </div>
              <div className='basis-1/3 flex-1 '>
                <Image src={web6} className=" rounded-lg object-cover" width={'100%'} height={"100%"} layout={'responsive'}/>
              </div>
            </div>
        </section>
        </div>
      </main>
    </div>
  )
}
